spring:
  config:
    activate:
      on-profile: dev
  application:
    name: animeRecommendationSystem
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/animerecoapp
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:

      ddl-auto: validate

    show-sql: true
    properties:
      hibernate:
        "format_sql": true
        "generate_statistics": true
debug: true
logging:
  level:
    org:
      hibernate:
        sql: debug
        type:
          descriptor:
            sql:
              spi: trace
        stat: DEBUG
    root: INFO
    cz:
      kocabek:
        animerecomedationsystem: debug
